Repository nock/nock, pull requests merged in 2019-08, with the labels that each got.

#1596 Async Reply functions (always emit errors)
  README.md
  lib/request_overrider.js
  tests/test_reply_function_async.js
Labels: breaking-change, feature

#1653 bug(recorder): replace qs lib with native querystring
  lib/recorder.js
Labels: bug

#1664 bug(overrider): unmocked HTTPS request with partial interceptor match
  lib/request_overrider.js
  tests/test_allow_unmocked_https.js
Labels: bug

#1109 Add test case for conflict between hostnames (#1108)
  tests/test_intercept.js
Labels: has-failing-test, help wanted, pinned
