Repository nock/nock, pull requests merged in 2020-02, with the labels that each got.

#1879 fix(types): Scope accepts legacy Url not WHATWG
  lib/scope.js
  tests/test_scope.js
  types/tests.ts
Labels: types

#1878 Greenkeeper/semantic release 17.0.2
  package-lock.json
  package.json
Labels: dependencies

#1887 Bump lolex and sinon
  package-lock.json
  package.json
  tests/test_fake_timer.js
  tests/test_reply_headers.js
Labels: dependencies

#1873 Drop support for String constructor
  lib/back.js
  lib/common.js
  lib/intercept.js
Labels: breaking-change

#1872 Do not return the `nock` global from `cleanAll()`
  index.js
Labels: breaking-change

#1895 Require Node 10+
  .github/workflows/continuous-integration.yaml
  package.json
Labels: breaking-change
